### ISSUE TITLE
Clarification on #2 

### ISSUE THREAD

**Issue by KniyaD** [act-hydro/GLY606_2024#6]
I am a bit confused about the setup for number 2. 

So far, I have this for part 1. I am a bit confused on if this is what you mean by file directory 
# ======================== #
# Start replacing site-specific info #
# ======================== #
# We will use "sed" command.
# We need to replace the site-specific information to unique placeholders.
# Step 1: Identify site-specific information
#         Site Name                  : US-SRG           --> use "REGION"
__**#         static_file      : "./ameriflux_static_fields.C1152.US-SRG.nc" --> use "STATIC"
#         init_file        : "./ameriflux_init_fields.C1152.US-SRG.2009-12-31_23-00-00.nc" --> use "INIT"
#         forcing_dir      : "forcing/US-SRG" --> use "FORCING"**__ 
#         Date for initial cond file : 2009-12-31       --> use "DATE_IC"
#         Start date                 : 2010-01-01       --> use "START_DATE"
#         # of run days              : 365              --> use "RUN_DAYS"

# Rule: Do not overwrite the source files
source_file="ufs-land.namelist.US-SRG"
temp_file="ufs-land.namelist.template"

# Following line: 1) replace "US-SRG" using "REGION" and 2) create new template file
sed "s#US-SRG#REGION#g" ${source_file} > ${temp_file}

# The option "-i" means direct modification to the file
sed -i "s#2009-12-31#DATE_IC#g" ${temp_file}
sed -i "s#2010-01-01#START_DATE#g" ${temp_file}
sed -i "s#365#RUN_DAYS#g" ${temp_file}
sed -i "s#./ameriflux_static_fields.C1152.US-SRG.nc#STATIC#g" ${temp_file}
sed -i "s#./ameriflux_init_fields.C1152.US-SRG.2009-12-31_23-00-00.nc#INIT#g" ${temp_file}
sed -i "s#forcing/US-SRG#FORCING#g" ${temp_file}

For pt 2 I am very confused 

# Define the targeted output folder
odir="./model_run/$REGION"  # is this what you meant when you said "each site should be located in model_run/<site_name>"

# check whether the targeted output folder exists
# if this folder does not exist, create it
if [ ! -f ${odir} ]; then
        mkdir ${odir}
fi

# ======================== #
# Step 2: create config files for each site #
# ======================== #

# read the site information 
for line in `ufs-land.namelist.US-SRG`; do

        # Split the strings by comma ","
        IFS=",";
        set -- $line
        site_id=$1
        date_ic=$2
        start_date=$3
        run_days=$5
# Do I add the file directory here ?#
        unset IFS

**Comment by act-hydro** [comment]
Problem solved by meeting offline!
