### ISSUE TITLE
reshape matrix error 

### ISSUE THREAD

**Issue by KniyaD** [act-hydro/GLY606_2024#8]
I keep getting this error when I try to reshape the sin and cos matrix
<img width="867" alt="Screenshot 2024-09-27 at 9 00 10 AM" src="https://github.com/user-attachments/assets/9e3a32a9-a41f-41fa-a182-cc8c5ddc0d40">

when I get rid of the sin and cos the error goes away.

**Comment by act-hydro** [comment]
@KniyaD As it showed up in the error message, it seems that the `x_1d_sin` variable is a `subplot` object, rather than an array?

**Comment by KniyaD** [comment]
Thank you, I was able to fix the problem.
